books/urls.py
from django.urls import path

from . import views

app_name = "books"
urlpatterns = [
    # ex: /books/
    path("", views.IndexView.as_view(), name="index"),
    # ex: /books/4
    path("<int:pk>/", views.DetailView.as_view(), name="detail")
]

myreads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("books/", include("books.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=100)

    # Need to add image
    cover = models.ImageField(null=True, blank=True)

    author = models.CharField(max_length=100)
    read_date = models.DateField()
    rating = models.PositiveSmallIntegerField()
    review = models.TextField(max_length=2000)

    def __str__(self):
        return self.title

books/views.py
from django.shortcuts import render
from django.views import generic

from .models import Book


class IndexView(generic.ListView):
    model = Book
    template_name = "books/index.html"


class DetailView(generic.DetailView):
    model = Book
    template_name = "books/detail.html"

books/templates/books/detail.html
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <title> myReads - book details </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'books/books.css' %}">
    <link rel="stylesheet" href="{% static 'books/detail.css' %}">
</head>
<body>
    <h1> View/Edit Book Details </h1>
    <form action="/book/update" method="post">
        <h2>Title</h2>
        <input
            id="title"
            type="text"
            name="title_field"
            value="{{ book.title }}" />
    </form>
</body>
</html>

books/templates/books/index.html
<!-- {% load static %}
<link rel="stylesheet" href="{% static 'books/style.css' %}"> -->

<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <title> myReads - all books </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'books/books.css' %}">
    <link rel="stylesheet" href="{% static 'books/index.css' %}">
</head>
<body>
    <h1>myReads</h1>
    <table>
        <colgroup>
            <col/>
            <col/>
            <col class="rating_col"/>
            <col/>
        </colgroup>
        <tr>
            <th>Cover</th>
            <th>Title</th>
            <th>Author</th>
            <th>Rating</th>
            <th>View/Edit</th>
        </tr>
        {% for book in book_list %}
        <tr>
            <td class="book_cover">
                <img src="{{ MEDIA_URL }}/{{book.cover}}" alt="book cover">
            </td>
            <td>{{ book.title }}</td>
            <td>{{ book.author }}</td>
            <td>{{ book.rating }}/5</td>
            <td class="pencil_icon"> 
                <img src="{% static 'books/pencil.jpeg' %}" 
                    alt="pencil icon">
            </td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>